module.exports = {
  content: [
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "bg-1": "var(--bg-1)",
        "bg-2": "var(--bg-2)",
        "brand-1": "var(--brand-1)",
        "brand-2": "var(--brand-2)",
        css: "var(--css)",
        grey: "var(--grey)",
        html: "var(--html)",
        js: "var(--js)",
        react: "var(--react)",
        "wf-base500": "var(--wf-base500)",
        "wf-base800": "var(--wf-base800)",
        white: "var(--white)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        "BG-text-u": "var(--BG-text-u-font-family)",
        "button-u": "var(--button-u-font-family)",
        "code-m": "var(--code-m-font-family)",
        "h1-u": "var(--h1-u-font-family)",
        "h2-m": "var(--h2-m-font-family)",
        "h2-u": "var(--h2-u-font-family)",
        "label-u-l": "var(--label-u-l-font-family)",
        "label-u-m": "var(--label-u-m-font-family)",
        "logo-m": "var(--logo-m-font-family)",
        "media-m": "var(--media-m-font-family)",
        "menu-m": "var(--menu-m-font-family)",
        "number-m": "var(--number-m-font-family)",
        "para-m": "var(--para-m-font-family)",
        "para-u": "var(--para-u-font-family)",
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      boxShadow: { "image-shadow": "var(--image-shadow)" },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [],
  darkMode: ["class"],
};
